# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 20:34
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='social_url')),
                ('avatar', models.ImageField(null=True, upload_to='')),
                ('name', models.CharField(max_length=63)),
                ('organization_name', models.CharField(blank=True, max_length=127)),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(max_length=5)),
                ('public_email', models.EmailField(blank=True, max_length=300)),
                ('public_website', models.URLField(blank=True, max_length=300)),
                ('social_url', models.CharField(max_length=300, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
