# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 20:40
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20171002_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='', max_length=63),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organization_name',
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='public_email',
            field=models.EmailField(max_length=254),
        ),
    ]
