# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20171002_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='public_website',
            field=models.URLField(blank=True, max_length=31),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='public_email',
            field=models.EmailField(blank=True, max_length=31),
        ),
    ]
