# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20171002_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='social_url',
            field=models.CharField(default='djangodbmodelsfieldscharfield', max_length=31),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=63),
        ),
    ]
