# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 15:33
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(unique=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField(max_length=5000)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('unit', models.CharField(choices=[(b'pound', b'POUND'), (b'gallon', b'GALLON'), (b'each', b'EACH')], default=b'each', max_length=80)),
                ('location', geoposition.fields.GeopositionField(max_length=42)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
