# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 20:40
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(unique_with=[b'user']),
        ),
    ]
